package com.kenyoung.orrery

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.io.BufferedInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.time.Instant
import kotlin.math.*

private val zodiacSymbols = mapOf(
    "Aries" to "\u2648\uFE0E",
    "Taurus" to "\u2649\uFE0E",
    "Gemini" to "\u264A\uFE0E",
    "Cancer" to "\u264B\uFE0E",
    "Leo" to "\u264C\uFE0E",
    "Virgo" to "\u264D\uFE0E",
    "Libra" to "\u264E\uFE0E",
    "Scorpius" to "\u264F\uFE0E",
    "Sagittarius" to "\u2650\uFE0E",
    "Capricornus" to "\u2651\uFE0E",
    "Aquarius" to "\u2652\uFE0E",
    "Pisces" to "\u2653\uFE0E",
)

private val planetSymbols = mapOf(
    "Sun" to "\u2609",       // ☉
    "Moon" to "\u263D",      // ☽
    "Mercury" to "\u263F",   // ☿
    "Venus" to "\u2640",     // ♀
    "Mars" to "\u2642",      // ♂
    "Jupiter" to "\u2643",   // ♃
    "Saturn" to "\u2644",    // ♄
    "Uranus" to "\u2645",    // ♅
    "Neptune" to "\u2646",   // ♆
)

private data class ObjectRow(
    val name: String,
    val constellation: String,
    val raString: String,
    val decString: String,
    val appRaHours: Double,
    val appDecDeg: Double
)

private const val DEC_MIN = -50.0
private const val DEC_MAX = 50.0
private const val DEC_RANGE = DEC_MAX - DEC_MIN

/**
 * Boundary segment in RA/Dec coordinates (B1875.0 hours/degrees).
 */
private data class MapSegment(
    val ra1: Double, val dec1: Double,
    val ra2: Double, val dec2: Double
)

private data class ZodiacLabel(
    val raHours: Double,
    val decDeg: Double,
    val symbol: String
)

private data class ZodiacMapData(
    val segments: List<MapSegment>,
    val labels: List<ZodiacLabel>
)

private val zodiacIndexToSymbol = mapOf(
    4 to "\u2652\uFE0E",   // Aquarius ♒
    6 to "\u2648\uFE0E",   // Aries ♈
    11 to "\u2651\uFE0E",  // Capricornus ♑
    21 to "\u264B\uFE0E",  // Cancer ♋
    37 to "\u264A\uFE0E",  // Gemini ♊
    45 to "\u264C\uFE0E",  // Leo ♌
    47 to "\u264E\uFE0E",  // Libra ♎
    66 to "\u2653\uFE0E",  // Pisces ♓
    71 to "\u264F\uFE0E",  // Scorpius ♏
    76 to "\u2650\uFE0E",  // Sagittarius ♐
    77 to "\u2649\uFE0E",  // Taurus ♉
    85 to "\u264D\uFE0E",  // Virgo ♍
)

/**
 * Loads precomputed zodiac boundary segments and label positions from assets.
 * Data generated by scripts/generateZodiacMapData.py.
 */
private fun loadZodiacMapData(context: android.content.Context): ZodiacMapData {
    val segments = mutableListOf<MapSegment>()
    val labels = mutableListOf<ZodiacLabel>()
    context.assets.open("zodiac_map_data.bin").use { raw ->
        BufferedInputStream(raw).use { stream ->
            val headerBuf = ByteArray(4)
            stream.read(headerBuf)
            val header = ByteBuffer.wrap(headerBuf).order(ByteOrder.LITTLE_ENDIAN)
            val segmentCount = header.short.toInt() and 0xFFFF
            val labelCount = header.short.toInt() and 0xFFFF

            val segBuf = ByteArray(16)
            val segBB = ByteBuffer.wrap(segBuf).order(ByteOrder.LITTLE_ENDIAN)
            for (i in 0 until segmentCount) {
                stream.read(segBuf)
                segBB.rewind()
                segments.add(MapSegment(
                    segBB.float.toDouble(), segBB.float.toDouble(),
                    segBB.float.toDouble(), segBB.float.toDouble()
                ))
            }

            val labelBuf = ByteArray(9)
            val labelBB = ByteBuffer.wrap(labelBuf).order(ByteOrder.LITTLE_ENDIAN)
            for (i in 0 until labelCount) {
                stream.read(labelBuf)
                labelBB.rewind()
                val ra = labelBB.float.toDouble()
                val dec = labelBB.float.toDouble()
                val idx = labelBuf[8].toInt() and 0xFF
                val symbol = zodiacIndexToSymbol[idx] ?: continue
                labels.add(ZodiacLabel(ra, dec, symbol))
            }
        }
    }
    return ZodiacMapData(segments, labels)
}

@Composable
fun ConstellationsScreen(instant: Instant) {
    val context = LocalContext.current
    ConstellationBoundary.ensureLoaded(context)

    val jd = instant.epochSecond.toDouble() / SECONDS_PER_DAY + UNIX_EPOCH_JD

    val bodies = listOf("Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")

    val rows = remember(instant) {
        bodies.map { name ->
            val state = AstroEngine.getBodyState(name, jd)
            val (appRa, appDec) = j2000ToApparent(state.ra, state.dec, jd)
            val (b1875Ra, b1875Dec) = precessJ2000ToDate(state.ra, state.dec, B1875_JD)
            val b1875RaHours = normalizeDegrees(b1875Ra) * DEGREES_TO_HOURS
            val constellationName = ConstellationBoundary.findConstellation(b1875RaHours, b1875Dec)
            val symbol = zodiacSymbols[constellationName]
            val constellation = buildString {
                append(constellationName)
                if (symbol != null) append("  $symbol")
            }
            val appRaHours = normalizeDegrees(appRa) * DEGREES_TO_HOURS
            val raStr = formatRa(appRaHours)
            val decStr = formatDec(appDec)
            ObjectRow(name, constellation, raStr, decStr, appRaHours, appDec)
        }
    }

    val mapData = remember { loadZodiacMapData(context) }

    val obliquity = remember(jd) {
        val t = (jd - J2000_JD) / DAYS_PER_JULIAN_CENTURY
        23.439291 - 0.0130042 * t
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .padding(horizontal = 12.dp, vertical = 8.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(
            text = "Constellations",
            style = TextStyle(color = LabelColor, fontSize = 20.sp, fontWeight = FontWeight.Bold),
            modifier = Modifier.padding(bottom = 8.dp)
        )

        // Two-column table: 5 rows of paired objects
        val pairs = listOf(
            rows[0] to rows[1],   // Sun | Moon
            rows[2] to rows[3],   // Mercury | Venus
            rows[4] to rows[5],   // Mars | Jupiter
            rows[6] to rows[7],   // Saturn | Uranus
            rows[8] to null       // Neptune | (empty)
        )

        for ((left, right) in pairs) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceEvenly
            ) {
                ObjectCell(left, modifier = Modifier.weight(1f))
                if (right != null) {
                    ObjectCell(right, modifier = Modifier.weight(1f))
                } else {
                    Spacer(modifier = Modifier.weight(1f))
                }
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        // Sky map
        Canvas(
            modifier = Modifier
                .fillMaxWidth()
                .aspectRatio(2f)
        ) {
            drawSkyMap(mapData.segments, mapData.labels, rows, obliquity)
        }
    }
}

@Composable
private fun ObjectCell(row: ObjectRow, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier.padding(horizontal = 4.dp, vertical = 2.dp)
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Text(
                text = row.name,
                style = TextStyle(
                    color = LabelColor,
                    fontSize = 14.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = FontFamily.SansSerif
                ),
                maxLines = 1
            )
            Text(
                text = "  ${row.constellation}",
                style = TextStyle(
                    color = Color.White,
                    fontSize = 14.sp,
                    fontFamily = FontFamily.SansSerif
                ),
                maxLines = 1
            )
        }
        Text(
            text = "${row.raString}  ${row.decString}",
            style = TextStyle(
                color = Color(0xFFAAAAAA),
                fontSize = 10.sp,
                fontFamily = FontFamily.Monospace
            ),
            maxLines = 1
        )
    }
}

private fun DrawScope.drawSkyMap(
    segments: List<MapSegment>,
    labels: List<ZodiacLabel>,
    rows: List<ObjectRow>,
    obliquity: Double
) {
    val w = size.width
    val h = size.height

    fun raToX(raHours: Double): Float {
        val chartRa = if (raHours > 12.0) raHours - 24.0 else raHours
        return (w * (12.0 - chartRa) / 24.0).toFloat()
    }

    fun decToY(dec: Double): Float {
        return (h * (DEC_MAX - dec) / DEC_RANGE).toFloat()
    }

    val boundaryColor = LabelColor
    val boundaryStroke = 1.5f

    // Draw zodiac boundary segments (J2025.0 coordinates, slightly tilted after precession)
    for (seg in segments) {
        val x1 = raToX(seg.ra1)
        val y1 = decToY(seg.dec1)
        val x2 = raToX(seg.ra2)
        val y2 = decToY(seg.dec2)
        if (abs(x1 - x2) <= w * 0.5f) {
            drawLine(boundaryColor, Offset(x1, y1), Offset(x2, y2), strokeWidth = boundaryStroke)
        } else {
            // Segment crosses RA=12h map edge — draw as two pieces
            val nearLeft: Offset
            val nearRight: Offset
            if (x1 < x2) {
                nearLeft = Offset(x1, y1); nearRight = Offset(x2, y2)
            } else {
                nearLeft = Offset(x2, y2); nearRight = Offset(x1, y1)
            }
            val dx = nearLeft.x + w - nearRight.x
            val tRight = (w - nearRight.x) / dx
            val yEdge = nearRight.y + tRight * (nearLeft.y - nearRight.y)
            drawLine(boundaryColor, nearRight, Offset(w, yEdge), strokeWidth = boundaryStroke)
            drawLine(boundaryColor, Offset(0f, yEdge), nearLeft, strokeWidth = boundaryStroke)
        }
    }

    // Celestial equator (Dec=0) — white horizontal
    val eqY = decToY(0.0)
    drawLine(Color.White, Offset(0f, eqY), Offset(w, eqY), strokeWidth = 1f)

    // Vernal Equinox (RA=0) — white vertical
    val veX = raToX(0.0)
    drawLine(Color.White, Offset(veX, 0f), Offset(veX, h), strokeWidth = 1f)

    // Ecliptic curve (red)
    val epsRad = Math.toRadians(obliquity)
    val eclipticPoints = (0..360).map { lambdaDeg ->
        val lambdaRad = Math.toRadians(lambdaDeg.toDouble())
        val ra = Math.toDegrees(atan2(sin(lambdaRad) * cos(epsRad), cos(lambdaRad)))
        val dec = Math.toDegrees(asin(sin(lambdaRad) * sin(epsRad)))
        val raH = normalizeDegrees(ra) * DEGREES_TO_HOURS
        Offset(raToX(raH), decToY(dec))
    }
    for (i in 0 until eclipticPoints.size - 1) {
        val p1 = eclipticPoints[i]
        val p2 = eclipticPoints[i + 1]
        if (abs(p1.x - p2.x) < w * 0.5f) {
            drawLine(Color.Red, p1, p2, strokeWidth = 1.5f)
        }
    }

    // Zodiac constellation symbols in white
    val zodiacPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.WHITE
        textSize = 36f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }

    // Planet symbols in green
    val symbolPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.GREEN
        textSize = 28f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }
    val fontMetrics = symbolPaint.fontMetrics
    val textVerticalOffset = -(fontMetrics.ascent + fontMetrics.descent) / 2f

    drawContext.canvas.nativeCanvas.let { canvas ->
        for (label in labels) {
            val x = raToX(label.raHours)
            val y = decToY(label.decDeg)
            canvas.drawText(label.symbol, x, y, zodiacPaint)
        }
        for (row in rows) {
            if (row.appDecDeg < DEC_MIN || row.appDecDeg > DEC_MAX) continue
            val x = raToX(row.appRaHours)
            val y = decToY(row.appDecDeg)
            val symbol = planetSymbols[row.name] ?: continue
            canvas.drawText(symbol, x, y + textVerticalOffset, symbolPaint)
        }
    }
}

/**
 * Formats RA in hours to "HH:MM:SS" with integer seconds.
 */
private fun formatRa(raHours: Double): String {
    var h = raHours % 24.0
    if (h < 0) h += 24.0
    var hh = floor(h).toInt()
    val rem = (h - hh) * 60.0
    var mm = floor(rem).toInt()
    var ss = round((rem - mm) * 60.0).toInt()
    if (ss >= 60) { ss -= 60; mm++ }
    if (mm >= 60) { mm -= 60; hh++ }
    if (hh >= 24) hh -= 24
    return "%02d:%02d:%02d".format(hh, mm, ss)
}

/**
 * Formats Dec in degrees to "+DD:MM:SS" with integer arc seconds.
 */
private fun formatDec(decDeg: Double): String {
    val sign = if (decDeg < 0) "-" else "+"
    val absDec = abs(decDeg)
    var dd = floor(absDec).toInt()
    val rem = (absDec - dd) * 60.0
    var mm = floor(rem).toInt()
    var ss = round((rem - mm) * 60.0).toInt()
    if (ss == 60) { ss = 0; mm++ }
    if (mm == 60) { mm = 0; dd++ }
    return "%s%02d:%02d:%02d".format(sign, dd, mm, ss)
}
