package com.kenyoung.orrery

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.layout.onSizeChanged
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import java.io.BufferedInputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.math.*

private val zodiacSymbols = mapOf(
    "Aries" to "\u2648\uFE0E",
    "Taurus" to "\u2649\uFE0E",
    "Gemini" to "\u264A\uFE0E",
    "Cancer" to "\u264B\uFE0E",
    "Leo" to "\u264C\uFE0E",
    "Virgo" to "\u264D\uFE0E",
    "Libra" to "\u264E\uFE0E",
    "Scorpius" to "\u264F\uFE0E",
    "Sagittarius" to "\u2650\uFE0E",
    "Capricornus" to "\u2651\uFE0E",
    "Aquarius" to "\u2652\uFE0E",
    "Pisces" to "\u2653\uFE0E",
)

private val planetSymbols = mapOf(
    "Sun" to "\u2609",       // ☉
    "Moon" to "\u263D",      // ☽
    "Mercury" to "\u263F",   // ☿
    "Venus" to "\u2640",     // ♀
    "Mars" to "\u2642",      // ♂
    "Jupiter" to "\u2643",   // ♃
    "Saturn" to "\u2644",    // ♄
    "Uranus" to "\u2645",    // ♅
    "Neptune" to "\u2646",   // ♆
)

private data class ObjectRow(
    val name: String,
    val constellation: String,
    val raString: String,
    val decString: String,
    val appRaHours: Double,
    val appDecDeg: Double
)

private const val DEC_MIN = -50.0
private const val DEC_MAX = 50.0
private const val DEC_RANGE = DEC_MAX - DEC_MIN

/**
 * Boundary segment in RA/Dec coordinates (B1875.0 hours/degrees).
 */
private data class MapSegment(
    val ra1: Double, val dec1: Double,
    val ra2: Double, val dec2: Double
)

private data class ZodiacLabel(
    val raHours: Double,
    val decDeg: Double,
    val symbol: String
)

private data class ZodiacMapData(
    val segments: List<MapSegment>,
    val labels: List<ZodiacLabel>
)

private val zodiacIndexToSymbol = mapOf(
    4 to "\u2652\uFE0E",   // Aquarius ♒
    6 to "\u2648\uFE0E",   // Aries ♈
    11 to "\u2651\uFE0E",  // Capricornus ♑
    21 to "\u264B\uFE0E",  // Cancer ♋
    37 to "\u264A\uFE0E",  // Gemini ♊
    45 to "\u264C\uFE0E",  // Leo ♌
    47 to "\u264E\uFE0E",  // Libra ♎
    66 to "\u2653\uFE0E",  // Pisces ♓
    71 to "\u264F\uFE0E",  // Scorpius ♏
    76 to "\u2650\uFE0E",  // Sagittarius ♐
    77 to "\u2649\uFE0E",  // Taurus ♉
    85 to "\u264D\uFE0E",  // Virgo ♍
)

private data class BrightStar(
    val raHours: Double,
    val decDeg: Double,
    val vmag: Double
)

/**
 * Loads bright star positions and magnitudes from assets.
 * Data generated by scripts/generateBrightStars.py.
 */
private fun loadBrightStars(context: android.content.Context): List<BrightStar> {
    val stars = mutableListOf<BrightStar>()
    context.assets.open("bright_stars.bin").use { raw ->
        BufferedInputStream(raw).use { stream ->
            val headerBuf = ByteArray(2)
            stream.read(headerBuf)
            val starCount = ByteBuffer.wrap(headerBuf).order(ByteOrder.LITTLE_ENDIAN)
                .short.toInt() and 0xFFFF

            val buf = ByteArray(12)
            val bb = ByteBuffer.wrap(buf).order(ByteOrder.LITTLE_ENDIAN)
            for (i in 0 until starCount) {
                stream.read(buf)
                bb.rewind()
                stars.add(BrightStar(
                    bb.float.toDouble(), bb.float.toDouble(), bb.float.toDouble()
                ))
            }
        }
    }
    return stars
}

/**
 * Loads precomputed zodiac boundary segments and label positions from assets.
 * Data generated by scripts/generateZodiacMapData.py.
 */
private fun loadZodiacMapData(context: android.content.Context): ZodiacMapData {
    val segments = mutableListOf<MapSegment>()
    val labels = mutableListOf<ZodiacLabel>()
    context.assets.open("zodiac_map_data.bin").use { raw ->
        BufferedInputStream(raw).use { stream ->
            val headerBuf = ByteArray(4)
            stream.read(headerBuf)
            val header = ByteBuffer.wrap(headerBuf).order(ByteOrder.LITTLE_ENDIAN)
            val segmentCount = header.short.toInt() and 0xFFFF
            val labelCount = header.short.toInt() and 0xFFFF

            val segBuf = ByteArray(16)
            val segBB = ByteBuffer.wrap(segBuf).order(ByteOrder.LITTLE_ENDIAN)
            for (i in 0 until segmentCount) {
                stream.read(segBuf)
                segBB.rewind()
                segments.add(MapSegment(
                    segBB.float.toDouble(), segBB.float.toDouble(),
                    segBB.float.toDouble(), segBB.float.toDouble()
                ))
            }

            val labelBuf = ByteArray(9)
            val labelBB = ByteBuffer.wrap(labelBuf).order(ByteOrder.LITTLE_ENDIAN)
            for (i in 0 until labelCount) {
                stream.read(labelBuf)
                labelBB.rewind()
                val ra = labelBB.float.toDouble()
                val dec = labelBB.float.toDouble()
                val idx = labelBuf[8].toInt() and 0xFF
                val symbol = zodiacIndexToSymbol[idx] ?: continue
                labels.add(ZodiacLabel(ra, dec, symbol))
            }
        }
    }
    return ZodiacMapData(segments, labels)
}

@Composable
fun ConstellationsScreen(
    displayEpoch: Double,
    currentInstant: Instant,
    stdOffsetHours: Double,
    stdTimeLabel: String,
    useStandardTime: Boolean,
    resetAnimTrigger: Int = 0,
    onAnimStoppedChange: (Boolean) -> Unit = {}
) {
    val context = LocalContext.current
    ConstellationBoundary.ensureLoaded(context)

    // --- ANIMATION STATE ---
    var isAnimating by remember { mutableStateOf(false) }
    var animDayOffset by remember { mutableStateOf(0.0) }

    // Report stopped state to parent; reset on trigger from parent
    LaunchedEffect(isAnimating, animDayOffset) {
        onAnimStoppedChange(!isAnimating && animDayOffset > 0.0)
    }
    LaunchedEffect(resetAnimTrigger) {
        if (resetAnimTrigger > 0) { animDayOffset = 0.0; isAnimating = false }
    }

    // Animation loop: 30 fps, 1/6 day (4 hours) per frame
    LaunchedEffect(isAnimating) {
        if (isAnimating) {
            while (isAnimating) {
                animDayOffset += 1.0 / 6.0
                delay(33)
            }
        }
    }

    // Compute effective JD
    val effectiveJD = if (isAnimating || animDayOffset > 0.0) {
        displayEpoch + animDayOffset + UNIX_EPOCH_JD
    } else {
        currentInstant.epochSecond.toDouble() / SECONDS_PER_DAY + UNIX_EPOCH_JD
    }
    val jd = effectiveJD

    // Date/time string for animation display
    val showDateTime = isAnimating || animDayOffset > 0.0
    val displayOffsetSeconds = if (useStandardTime) (stdOffsetHours * 3600).toLong() else 0L
    val displayZone = ZoneId.ofOffset("", java.time.ZoneOffset.ofTotalSeconds(displayOffsetSeconds.toInt()))
    val timeLabel = if (useStandardTime) stdTimeLabel else "UT"
    val dateStr = if (showDateTime) {
        val millis = Math.round((jd - UNIX_EPOCH_JD) * MILLIS_PER_DAY / 60000.0) * 60000L
        val displayInstant = Instant.ofEpochMilli(millis)
        DateTimeFormatter.ofPattern("dd/MM/yyyy").withZone(displayZone).format(displayInstant)
    } else ""
    val timeStr = if (showDateTime) {
        val millis = Math.round((jd - UNIX_EPOCH_JD) * MILLIS_PER_DAY / 60000.0) * 60000L
        val displayInstant = Instant.ofEpochMilli(millis)
        DateTimeFormatter.ofPattern("HH:mm").withZone(displayZone).format(displayInstant) + " $timeLabel"
    } else ""

    val bodies = listOf("Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")

    val rows = remember(jd) {
        bodies.map { name ->
            val state = AstroEngine.getBodyState(name, jd)
            val (appRa, appDec) = j2000ToApparent(state.ra, state.dec, jd)
            val (b1875Ra, b1875Dec) = precessJ2000ToDate(state.ra, state.dec, B1875_JD)
            val b1875RaHours = normalizeDegrees(b1875Ra) * DEGREES_TO_HOURS
            val constellationName = ConstellationBoundary.findConstellation(b1875RaHours, b1875Dec)
            val symbol = zodiacSymbols[constellationName]
            val displayName = when (constellationName) {
                "Capricornus" -> "Capricorn."
                "Sagittarius" -> "Sagittar."
                else -> constellationName
            }
            val constellation = buildString {
                append(displayName)
                if (symbol != null) append("  $symbol")
            }
            val appRaHours = normalizeDegrees(appRa) * DEGREES_TO_HOURS
            val raStr = formatRa(appRaHours)
            val decStr = formatDec(appDec)
            ObjectRow(name, constellation, raStr, decStr, appRaHours, appDec)
        }
    }

    val mapData = remember { loadZodiacMapData(context) }
    val brightStars = remember { loadBrightStars(context) }

    val obliquity = remember(jd) {
        val t = (jd - J2000_JD) / DAYS_PER_JULIAN_CENTURY
        23.439291 - 0.0130042 * t
    }

    val density = LocalDensity.current
    val headerHeightPx = remember { mutableStateOf(0) }
    val spacerBeforeMaps = 8.dp
    val spacerBetweenMaps = 24.dp

    BoxWithConstraints(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .padding(horizontal = 12.dp, vertical = 8.dp)
    ) {
        val maxWidthPx = with(density) { maxWidth.toPx() }
        val maxHeightPx = with(density) { maxHeight.toPx() }
        val spacersPx = with(density) { (spacerBeforeMaps + spacerBetweenMaps).toPx() }

        // Compute map width: full width unless both maps won't fit vertically
        val mapWidthDp = if (headerHeightPx.value > 0) {
            val availableForMaps = maxHeightPx - headerHeightPx.value - spacersPx
            val fittedWidthPx = availableForMaps * 1.8f  // 2 maps at aspect 3.6 each
            val mapPx = minOf(maxWidthPx, maxOf(fittedWidthPx, 0f))
            with(density) { mapPx.toDp() }
        } else {
            maxWidth  // First frame before measurement: use full width
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState()),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Header: title + table, measured to compute available map space
            Column(
                modifier = Modifier.onSizeChanged { headerHeightPx.value = it.height },
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth().padding(bottom = 8.dp),
                    horizontalArrangement = Arrangement.Center,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    if (showDateTime) {
                        Text(
                            text = dateStr,
                            style = TextStyle(color = Color.White, fontSize = 14.sp, fontFamily = FontFamily.Monospace),
                            modifier = Modifier.weight(1f)
                        )
                    } else {
                        Spacer(modifier = Modifier.weight(1f))
                    }
                    Text(
                        text = "Constellations",
                        style = TextStyle(color = LabelColor, fontSize = 20.sp, fontWeight = FontWeight.Bold)
                    )
                    if (showDateTime) {
                        Text(
                            text = timeStr,
                            style = TextStyle(color = Color.White, fontSize = 14.sp, fontFamily = FontFamily.Monospace),
                            modifier = Modifier.weight(1f),
                            textAlign = androidx.compose.ui.text.style.TextAlign.End
                        )
                    } else {
                        Spacer(modifier = Modifier.weight(1f))
                    }
                }

                val pairs = listOf(
                    rows[0] to rows[1],
                    rows[2] to rows[3],
                    rows[4] to rows[5],
                    rows[6] to rows[7],
                    rows[8] to null
                )

                for ((left, right) in pairs) {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceEvenly
                    ) {
                        ObjectCell(left, modifier = Modifier.weight(1f))
                        if (right != null) {
                            ObjectCell(right, modifier = Modifier.weight(1f))
                        } else {
                            Spacer(modifier = Modifier.weight(1f))
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(spacerBeforeMaps))

            // Constellation boundary map
            Canvas(
                modifier = Modifier
                    .width(mapWidthDp)
                    .aspectRatio(3.6f)
            ) {
                drawSkyMap(mapData.segments, mapData.labels, rows, obliquity)
            }

            Spacer(modifier = Modifier.height(spacerBetweenMaps))

            // Star map
            Canvas(
                modifier = Modifier
                    .width(mapWidthDp)
                    .aspectRatio(3.6f)
            ) {
                drawStarMap(brightStars, rows, obliquity)
            }

            Spacer(modifier = Modifier.height(16.dp))
            Button(
                onClick = { isAnimating = !isAnimating },
                colors = ButtonDefaults.buttonColors(
                    containerColor = if (isAnimating) Color.Red else Color.DarkGray,
                    contentColor = Color.White
                ),
                modifier = Modifier.height(36.dp),
                contentPadding = PaddingValues(horizontal = 12.dp)
            ) {
                Text(if (isAnimating) "Stop" else "Animate", fontSize = 14.sp)
            }
        }
    }
}

@Composable
private fun ObjectCell(row: ObjectRow, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier.padding(horizontal = 4.dp, vertical = 2.dp)
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.height(24.dp)
        ) {
            Text(
                text = row.name,
                style = TextStyle(
                    color = LabelColor,
                    fontSize = 14.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = FontFamily.SansSerif,
                    lineHeight = 24.sp
                ),
                maxLines = 1
            )
            Text(
                text = "  ${row.constellation}",
                style = TextStyle(
                    color = Color.White,
                    fontSize = 14.sp,
                    fontFamily = FontFamily.SansSerif,
                    lineHeight = 24.sp
                ),
                maxLines = 1
            )
        }
        Text(
            text = "${row.raString}  ${row.decString}",
            style = TextStyle(
                color = Color(0xFFAAAAAA),
                fontSize = 10.sp,
                fontFamily = FontFamily.Monospace,
                lineHeight = 14.sp
            ),
            maxLines = 1,
            modifier = Modifier.height(14.dp)
        )
    }
}

private fun DrawScope.drawSkyMap(
    segments: List<MapSegment>,
    labels: List<ZodiacLabel>,
    rows: List<ObjectRow>,
    obliquity: Double
) {
    val w = size.width
    val h = size.height

    fun raToX(raHours: Double): Float {
        val chartRa = if (raHours > 12.0) raHours - 24.0 else raHours
        return (w * (12.0 - chartRa) / 24.0).toFloat()
    }

    fun decToY(dec: Double): Float {
        return (h * (DEC_MAX - dec) / DEC_RANGE).toFloat()
    }

    // Border box
    drawRect(Color.Gray, style = androidx.compose.ui.graphics.drawscope.Stroke(1f))

    val boundaryColor = LabelColor
    val boundaryStroke = 2.25f

    // Draw zodiac boundary segments (J2025.0 coordinates, slightly tilted after precession)
    for (seg in segments) {
        val x1 = raToX(seg.ra1)
        val y1 = decToY(seg.dec1)
        val x2 = raToX(seg.ra2)
        val y2 = decToY(seg.dec2)
        if (abs(x1 - x2) <= w * 0.5f) {
            drawLine(boundaryColor, Offset(x1, y1), Offset(x2, y2), strokeWidth = boundaryStroke)
        } else {
            // Segment crosses RA=12h map edge — draw as two pieces
            val nearLeft: Offset
            val nearRight: Offset
            if (x1 < x2) {
                nearLeft = Offset(x1, y1); nearRight = Offset(x2, y2)
            } else {
                nearLeft = Offset(x2, y2); nearRight = Offset(x1, y1)
            }
            val dx = nearLeft.x + w - nearRight.x
            val tRight = (w - nearRight.x) / dx
            val yEdge = nearRight.y + tRight * (nearLeft.y - nearRight.y)
            drawLine(boundaryColor, nearRight, Offset(w, yEdge), strokeWidth = boundaryStroke)
            drawLine(boundaryColor, Offset(0f, yEdge), nearLeft, strokeWidth = boundaryStroke)
        }
    }

    // Celestial equator (Dec=0) — white horizontal
    val eqY = decToY(0.0)
    drawLine(Color.White, Offset(0f, eqY), Offset(w, eqY), strokeWidth = 1f)

    // Vernal Equinox (RA=0) — white vertical
    val veX = raToX(0.0)
    drawLine(Color.White, Offset(veX, 0f), Offset(veX, h), strokeWidth = 1f)

    // Ecliptic curve (red)
    val epsRad = Math.toRadians(obliquity)
    val eclipticPoints = (0..360).map { lambdaDeg ->
        val lambdaRad = Math.toRadians(lambdaDeg.toDouble())
        val ra = Math.toDegrees(atan2(sin(lambdaRad) * cos(epsRad), cos(lambdaRad)))
        val dec = Math.toDegrees(asin(sin(lambdaRad) * sin(epsRad)))
        val raH = normalizeDegrees(ra) * DEGREES_TO_HOURS
        Offset(raToX(raH), decToY(dec))
    }
    for (i in 0 until eclipticPoints.size - 1) {
        val p1 = eclipticPoints[i]
        val p2 = eclipticPoints[i + 1]
        if (abs(p1.x - p2.x) < w * 0.5f) {
            drawLine(Color.Red, p1, p2, strokeWidth = 3.0f)
        }
    }

    // Zodiac constellation symbols in white
    val zodiacPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.WHITE
        textSize = 36f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }

    // Planet symbols in green
    val symbolPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.GREEN
        textSize = 28f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }
    val fontMetrics = symbolPaint.fontMetrics
    val textVerticalOffset = -(fontMetrics.ascent + fontMetrics.descent) / 2f

    // Ophiuchus label — no Unicode symbol, so draw name in white at planet symbol size
    val ophiuchusPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.WHITE
        textSize = 28f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }

    drawContext.canvas.nativeCanvas.let { canvas ->
        for (label in labels) {
            val x = raToX(label.raHours)
            val y = decToY(label.decDeg - 3.0)
            canvas.drawText(label.symbol, x, y, zodiacPaint)
        }
        // Ophiuchus text at RA 18h15m, Dec +9°30'
        canvas.drawText("Ophiuchus", raToX(17.75), decToY(18.0), ophiuchusPaint)
        for (row in rows) {
            if (row.appDecDeg < DEC_MIN || row.appDecDeg > DEC_MAX) continue
            val x = raToX(row.appRaHours)
            val y = decToY(row.appDecDeg)
            val symbol = planetSymbols[row.name] ?: continue
            canvas.drawText(symbol, x, y + textVerticalOffset, symbolPaint)
        }
    }
}

private fun DrawScope.drawStarMap(
    stars: List<BrightStar>,
    rows: List<ObjectRow>,
    obliquity: Double
) {
    val w = size.width
    val h = size.height

    fun raToX(raHours: Double): Float {
        val chartRa = if (raHours > 12.0) raHours - 24.0 else raHours
        return (w * (12.0 - chartRa) / 24.0).toFloat()
    }

    fun decToY(dec: Double): Float {
        return (h * (DEC_MAX - dec) / DEC_RANGE).toFloat()
    }

    // Border box
    drawRect(Color.Gray, style = androidx.compose.ui.graphics.drawscope.Stroke(1f))

    // Stars — size and brightness scale with magnitude
    // Magnitude range: ~-1.5 (Sirius) to 3.0
    val magMin = -1.5  // brightest
    val magMax = 3.5   // faintest
    val magRange = magMax - magMin
    val maxRadius = 5f
    val minRadius = 1f

    for (star in stars) {
        if (star.decDeg < DEC_MIN || star.decDeg > DEC_MAX) continue
        val x = raToX(star.raHours)
        val y = decToY(star.decDeg)
        val t = ((star.vmag - magMin) / magRange).coerceIn(0.0, 1.0)
        val radius = (maxRadius + (minRadius - maxRadius) * t).toFloat()
        val shade = (255 * (1.0 - t * 0.6)).toInt()  // brightest=255, faintest=102
        drawCircle(
            color = Color(shade, shade, shade),
            radius = radius,
            center = Offset(x, y)
        )
    }

    // Celestial equator (Dec=0)
    val eqY = decToY(0.0)
    drawLine(Color.White, Offset(0f, eqY), Offset(w, eqY), strokeWidth = 1f)

    // Vernal Equinox (RA=0)
    val veX = raToX(0.0)
    drawLine(Color.White, Offset(veX, 0f), Offset(veX, h), strokeWidth = 1f)

    // Ecliptic curve (red)
    val epsRad = Math.toRadians(obliquity)
    val eclipticPoints = (0..360).map { lambdaDeg ->
        val lambdaRad = Math.toRadians(lambdaDeg.toDouble())
        val ra = Math.toDegrees(atan2(sin(lambdaRad) * cos(epsRad), cos(lambdaRad)))
        val dec = Math.toDegrees(asin(sin(lambdaRad) * sin(epsRad)))
        val raH = normalizeDegrees(ra) * DEGREES_TO_HOURS
        Offset(raToX(raH), decToY(dec))
    }
    for (i in 0 until eclipticPoints.size - 1) {
        val p1 = eclipticPoints[i]
        val p2 = eclipticPoints[i + 1]
        if (abs(p1.x - p2.x) < w * 0.5f) {
            drawLine(Color.Red, p1, p2, strokeWidth = 3.0f)
        }
    }

    // Planet symbols in green
    val symbolPaint = android.graphics.Paint().apply {
        color = android.graphics.Color.GREEN
        textSize = 28f
        textAlign = android.graphics.Paint.Align.CENTER
        isAntiAlias = true
    }
    val fontMetrics = symbolPaint.fontMetrics
    val textVerticalOffset = -(fontMetrics.ascent + fontMetrics.descent) / 2f

    drawContext.canvas.nativeCanvas.let { canvas ->
        for (row in rows) {
            if (row.appDecDeg < DEC_MIN || row.appDecDeg > DEC_MAX) continue
            val x = raToX(row.appRaHours)
            val y = decToY(row.appDecDeg)
            val symbol = planetSymbols[row.name] ?: continue
            canvas.drawText(symbol, x, y + textVerticalOffset, symbolPaint)
        }
    }
}

/**
 * Formats RA in hours to "HH:MM:SS" with integer seconds.
 */
private fun formatRa(raHours: Double): String {
    var h = raHours % 24.0
    if (h < 0) h += 24.0
    var hh = floor(h).toInt()
    val rem = (h - hh) * 60.0
    var mm = floor(rem).toInt()
    var ss = round((rem - mm) * 60.0).toInt()
    if (ss >= 60) { ss -= 60; mm++ }
    if (mm >= 60) { mm -= 60; hh++ }
    if (hh >= 24) hh -= 24
    return "%02d:%02d:%02d".format(hh, mm, ss)
}

/**
 * Formats Dec in degrees to "+DD:MM:SS" with integer arc seconds.
 */
private fun formatDec(decDeg: Double): String {
    val sign = if (decDeg < 0) "-" else "+"
    val absDec = abs(decDeg)
    var dd = floor(absDec).toInt()
    val rem = (absDec - dd) * 60.0
    var mm = floor(rem).toInt()
    var ss = round((rem - mm) * 60.0).toInt()
    if (ss == 60) { ss = 0; mm++ }
    if (mm == 60) { mm = 0; dd++ }
    return "%s%02d:%02d:%02d".format(sign, dd, mm, ss)
}
