package com.kenyoung.orrery

import android.graphics.Paint
import android.graphics.Path
import android.graphics.Typeface
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.drawIntoCanvas
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import java.time.Instant
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.ZonedDateTime
import kotlin.math.abs
import kotlin.math.floor

private const val FORECAST_DAYS = 365
private const val SAMPLE_STEP_DAYS = 1.0
private const val SAMPLE_COUNT = FORECAST_DAYS + 1
private const val ARCSEC_PER_RAD = 206264.806
private const val AU_KM = 149597870.7

// Equatorial radii, km. Saturn radius is the planet disk only; rings handled separately.
private val PLANET_RADIUS_KM = mapOf(
    "Mercury" to 2439.7,
    "Venus"   to 6051.8,
    "Mars"    to 3389.5,
    "Jupiter" to 69911.0,
    "Saturn"  to 58232.0,
    "Uranus"  to 25362.0,
    "Neptune" to 24622.0,
)

// Outer edge of Saturn's A ring (km). Treated as full ring-system extent regardless of tilt.
private const val SATURN_RING_OUTER_RADIUS_KM = 136775.0

// Theoretical max geocentric angular diameter (arcsec) at closest possible approach
// (Earth at perihelion / aphelion paired with planet at opposite apsis).
// Generated by scripts/calculateMaxAngularSizes.py. Saturn value includes the A ring.
private val MAX_DIAMETER_ARCSEC = mapOf(
    "Mercury" to 13.02,
    "Venus"   to 65.43,
    "Mars"    to 25.63,
    "Jupiter" to 49.01,
    "Saturn"  to 47.10,
    "Uranus"  to  4.05,
    "Neptune" to  2.36,
)

// Minimum clearance between any two adjacent planet curves, in arcsec.
private const val MIN_GAP_ARCSEC = 5.0

private val MONTH_ABBREV = arrayOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

private data class PlanetSeries(
    val name: String,
    val symbol: String,
    val color: Color,
    val colorInt: Int,
    val samplesArcsec: FloatArray,
    val ringSamplesArcsec: FloatArray?,
)

private data class MonthTick(val dayOffset: Double, val month: Int, val year: Int)

@Composable
fun PlanetAngularSizeScreen(obs: ObserverState, onTimeDisplayChange: (Boolean) -> Unit) {
    // Left swipe advances (future), right swipe rewinds (past) — matches the natural
    // page-turn gesture where dragging content leftward reveals what's to the right.
    var yearOffset by remember { mutableStateOf(0) }

    val shiftedEpochSec = obs.now.epochSecond + yearOffset.toLong() * FORECAST_DAYS.toLong() * SECONDS_PER_DAY.toLong()
    val startJd = shiftedEpochSec.toDouble() / SECONDS_PER_DAY + UNIX_EPOCH_JD
    val dayKey = shiftedEpochSec / SECONDS_PER_DAY.toLong()

    val planets = remember { getOrreryPlanets().filter { it.name != "Earth" } }

    // Recomputed once per day — 7 planets × 366 samples per recomp would be wasteful per-minute.
    val series: List<PlanetSeries> = remember(dayKey) {
        planets.map { p ->
            val radiusKm = PLANET_RADIUS_KM[p.name] ?: 0.0
            val hasRings = p.name == "Saturn"
            val samples = FloatArray(SAMPLE_COUNT)
            val ringSamples = if (hasRings) FloatArray(SAMPLE_COUNT) else null
            for (i in 0 until SAMPLE_COUNT) {
                val jd = startJd + i * SAMPLE_STEP_DAYS
                val state = AstroEngine.getBodyState(p.name, jd)
                val distKm = state.distGeo * AU_KM
                samples[i] = (2.0 * radiusKm / distKm * ARCSEC_PER_RAD).toFloat()
                if (hasRings) {
                    ringSamples!![i] = (2.0 * SATURN_RING_OUTER_RADIUS_KM / distKm * ARCSEC_PER_RAD).toFloat()
                }
            }
            PlanetSeries(p.name, p.symbol, p.color, p.color.toArgb(), samples, ringSamples)
        }
    }

    val maxDiameters = remember(planets) { planets.map { MAX_DIAMETER_ARCSEC[it.name] ?: 0.0 } }
    val totalArcsecNeeded = remember(maxDiameters) {
        maxDiameters.sum() + MIN_GAP_ARCSEC * (maxDiameters.size + 1)
    }
    val baselineArcsec = remember(maxDiameters) {
        DoubleArray(maxDiameters.size).apply {
            var cursor = MIN_GAP_ARCSEC
            for (i in maxDiameters.indices) {
                cursor += maxDiameters[i] / 2.0
                this[i] = cursor
                cursor += maxDiameters[i] / 2.0 + MIN_GAP_ARCSEC
            }
        }
    }
    val tickLaneIdx = remember(maxDiameters) {
        maxDiameters.indices.maxByOrNull { maxDiameters[it] } ?: 0
    }

    val zone: ZoneId = if (obs.useStandardTime)
        ZoneOffset.ofTotalSeconds((obs.stdOffsetHours * 3600).toInt())
    else
        ZoneOffset.UTC

    val monthTicks: List<MonthTick> = remember(dayKey, zone) {
        val startInstant = Instant.ofEpochSecond(shiftedEpochSec)
        val endInstant = startInstant.plusSeconds(FORECAST_DAYS.toLong() * SECONDS_PER_DAY.toLong())
        val startLocal = ZonedDateTime.ofInstant(startInstant, zone)
        var cursor = startLocal.withDayOfMonth(1).withHour(0).withMinute(0).withSecond(0).withNano(0).plusMonths(1)
        val out = mutableListOf<MonthTick>()
        while (!cursor.toInstant().isAfter(endInstant)) {
            val tickEpochSec = cursor.toInstant().epochSecond
            val dayOffset = (tickEpochSec - shiftedEpochSec).toDouble() / SECONDS_PER_DAY
            out.add(MonthTick(dayOffset, cursor.monthValue, cursor.year))
            cursor = cursor.plusMonths(1)
        }
        out
    }
    // For section 0 (left of the first month tick) we need the month we started in.
    val startMonthOneBased = ZonedDateTime.ofInstant(Instant.ofEpochSecond(shiftedEpochSec), zone).monthValue

    val axisPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            strokeWidth = 1.5f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }
    val baselinePaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0x55, 0x55, 0x55)
            strokeWidth = 1f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }
    val labelPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            textSize = 22f
            typeface = Typeface.MONOSPACE
            isAntiAlias = true
            textAlign = Paint.Align.RIGHT
        }
    }
    val monthLetterPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            textSize = 28f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val yearPaint = remember {
        Paint().apply {
            color = android.graphics.Color.WHITE
            textSize = 44f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val symbolPaint = remember {
        Paint().apply {
            textSize = 32f
            typeface = Typeface.DEFAULT_BOLD
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val lemonFillPaint = remember {
        Paint().apply {
            style = Paint.Style.FILL
            isAntiAlias = true
        }
    }
    val lemonPath = remember { Path() }
    val janTickPaint = remember {
        Paint().apply {
            color = android.graphics.Color.YELLOW
            strokeWidth = 4.5f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }

    Box(modifier = Modifier.fillMaxSize()) {
    Canvas(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .pointerInput(Unit) {
                val swipeThresholdPx = with(density) { 50.dp.toPx() }
                var dragAccum = 0f
                detectHorizontalDragGestures(
                    onDragStart = { dragAccum = 0f },
                    onDragCancel = { dragAccum = 0f },
                    onDragEnd = {
                        when {
                            dragAccum > swipeThresholdPx -> yearOffset -= 1
                            dragAccum < -swipeThresholdPx -> yearOffset += 1
                        }
                        dragAccum = 0f
                    },
                    onHorizontalDrag = { _, amount -> dragAccum += amount }
                )
            }
    ) {
        withDensityScaling { w, h ->

        val leftMargin = 80f
        val rightMargin = 15f
        val topMargin = 35f
        val bottomMargin = 125f

        val chartLeft = leftMargin
        val chartRight = w - rightMargin
        val chartTop = topMargin
        val chartBottom = h - bottomMargin
        val chartWidth = chartRight - chartLeft
        val chartHeight = chartBottom - chartTop

        val pxPerArcsec = chartHeight.toDouble() / totalArcsecNeeded

        fun dayToX(dayOffset: Double): Float =
            (chartLeft + (dayOffset / FORECAST_DAYS) * chartWidth).toFloat()
        fun laneCenterY(laneIdx: Int): Float = (chartTop + baselineArcsec[laneIdx] * pxPerArcsec).toFloat()

        drawIntoCanvas { nc ->
            val canvas = nc.nativeCanvas

            for ((i, s) in series.withIndex()) {
                val y = laneCenterY(i)
                canvas.drawLine(chartLeft, y, chartRight, y, baselinePaint)
                symbolPaint.color = s.colorInt
                canvas.drawText(s.symbol, leftMargin - 22f, y + 11f, symbolPaint)
            }

            // Ticks anchored to the largest lane so the full ±halfMax range fits within its band.
            val tickLaneSpanArcsec = maxDiameters[tickLaneIdx]
            val tickLaneY = laneCenterY(tickLaneIdx)
            val halfMax = tickLaneSpanArcsec / 2.0
            val tickStep = when {
                tickLaneSpanArcsec >= 80.0 -> 20.0
                tickLaneSpanArcsec >= 30.0 -> 10.0
                tickLaneSpanArcsec >= 12.0 -> 5.0
                else -> 2.0
            }
            var tickArcsec = -floor(halfMax / tickStep) * tickStep
            while (tickArcsec <= halfMax) {
                val y = tickLaneY + (tickArcsec * pxPerArcsec).toFloat()
                canvas.drawLine(leftMargin - 6f, y, leftMargin, y, axisPaint)
                // Skip the 0″ label — it sits at the tick-anchor lane's baseline and would
                // overlap that planet's symbol drawn at the same y.
                if (abs(tickArcsec) >= 0.001) {
                    val label = "%.0f\u2033".format(abs(tickArcsec))
                    canvas.drawText(label, leftMargin - 8f, y + 7f, labelPaint)
                }
                tickArcsec += tickStep
            }

            fun buildLemon(baselineY: Float, samples: FloatArray) {
                lemonPath.reset()
                for (k in 0 until SAMPLE_COUNT) {
                    val x = dayToX(k * SAMPLE_STEP_DAYS)
                    val y = baselineY - (samples[k] / 2.0 * pxPerArcsec).toFloat()
                    if (k == 0) lemonPath.moveTo(x, y) else lemonPath.lineTo(x, y)
                }
                for (k in SAMPLE_COUNT - 1 downTo 0) {
                    val x = dayToX(k * SAMPLE_STEP_DAYS)
                    val y = baselineY + (samples[k] / 2.0 * pxPerArcsec).toFloat()
                    lemonPath.lineTo(x, y)
                }
                lemonPath.close()
            }
            for ((i, s) in series.withIndex()) {
                val baselineY = laneCenterY(i)
                // Rings drawn first (wider, white) so the disk lemon overlays them.
                if (s.ringSamplesArcsec != null) {
                    buildLemon(baselineY, s.ringSamplesArcsec)
                    lemonFillPaint.color = android.graphics.Color.WHITE
                    canvas.drawPath(lemonPath, lemonFillPaint)
                }
                buildLemon(baselineY, s.samplesArcsec)
                lemonFillPaint.color = s.colorInt
                canvas.drawPath(lemonPath, lemonFillPaint)
            }

            val tickY = chartBottom
            val tickLen = 6f
            val janTickLen = tickLen * 10f
            for (t in monthTicks) {
                val x = dayToX(t.dayOffset)
                if (t.month == 1) {
                    canvas.drawLine(x, tickY, x, tickY + janTickLen, janTickPaint)
                } else {
                    canvas.drawLine(x, tickY, x, tickY + tickLen, axisPaint)
                }
            }

            // Section i (0-based) covers the month starting at tick i-1, or for i=0 the month
            // in which the forecast starts.
            val letterY = chartBottom + 35f
            val boundaries = mutableListOf<Float>()
            boundaries.add(chartLeft)
            for (t in monthTicks) boundaries.add(dayToX(t.dayOffset))
            boundaries.add(chartRight)
            for (i in 0 until boundaries.size - 1) {
                val leftX = boundaries[i]
                val rightX = boundaries[i + 1]
                if (rightX - leftX < 14f) continue
                val monthOneBased = if (i == 0) startMonthOneBased else monthTicks[i - 1].month
                val label = MONTH_ABBREV[monthOneBased - 1]
                val cx = (leftX + rightX) / 2f
                monthLetterPaint.color = if (monthOneBased == 1)
                    android.graphics.Color.YELLOW
                else
                    android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
                canvas.save()
                canvas.rotate(90f, cx, letterY)
                canvas.drawText(label, cx, letterY, monthLetterPaint)
                canvas.restore()
            }

            val yearY = chartBottom + 105f
            for (t in monthTicks) {
                if (t.month != 7) continue
                val label = t.year.toString()
                val halfWidth = yearPaint.measureText(label) / 2f
                // If the July-1 tick sits too close to an edge, shift the label toward
                // the center just enough to keep it fully on-screen.
                val x = dayToX(t.dayOffset).coerceIn(chartLeft + halfWidth, chartRight - halfWidth)
                canvas.drawText(label, x, yearY, yearPaint)
            }
        }

        }
    }

    if (yearOffset != 0) {
        TextButton(
            onClick = { yearOffset = 0 },
            colors = ButtonDefaults.textButtonColors(contentColor = Color(0xFF00FF00)),
            modifier = Modifier.align(Alignment.TopEnd).padding(8.dp)
        ) {
            Text("Reset Time", fontWeight = FontWeight.Bold)
        }
    }
    }
}
