package com.kenyoung.orrery

import android.graphics.Paint
import android.graphics.Path
import android.graphics.Typeface
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxScope
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.drawIntoCanvas
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.time.Instant
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.exp
import kotlin.math.floor
import kotlin.math.log10
import kotlin.math.sin

private const val FORECAST_DAYS = 365
private const val SAMPLE_STEP_DAYS = 1.0
private const val SAMPLE_COUNT = FORECAST_DAYS + 1
private const val ARCSEC_PER_RAD = 206264.806
private const val AU_KM = 149597870.7

// Equatorial radii, km. Saturn radius is the planet disk only; rings handled separately.
private val PLANET_RADIUS_KM = mapOf(
    "Mercury" to 2439.7,
    "Venus"   to 6051.8,
    "Mars"    to 3389.5,
    "Jupiter" to 69911.0,
    "Saturn"  to 58232.0,
    "Uranus"  to 25362.0,
    "Neptune" to 24622.0,
)

// Outer edge of Saturn's A ring (km). Treated as full ring-system extent regardless of tilt.
private const val SATURN_RING_OUTER_RADIUS_KM = 136775.0

// Theoretical max geocentric angular diameter (arcsec) at closest possible approach
// (Earth at perihelion / aphelion paired with planet at opposite apsis).
// Generated by scripts/calculateMaxAngularSizes.py. Saturn value includes the A ring.
private val MAX_DIAMETER_ARCSEC = mapOf(
    "Mercury" to 13.02,
    "Venus"   to 65.43,
    "Mars"    to 25.63,
    "Jupiter" to 49.01,
    "Saturn"  to 47.10,
    "Uranus"  to  4.05,
    "Neptune" to  2.36,
)

// Minimum clearance between any two adjacent planet curves, in arcsec.
private const val MIN_GAP_ARCSEC = 1.0

// Wider gap between the Uranus and Neptune lanes. Their lemons are tiny, so their
// labels stack close together; extra vertical space keeps them legible.
private const val URANUS_NEPTUNE_GAP_ARCSEC = 5.0

// Chart's left margin in reference pixels. Referenced from both the drawing code
// and the tap-line state (which snaps to the left edge on year-shift).
private const val CHART_LEFT_MARGIN = 80f

private val YEAR_BUTTON_PADDING = PaddingValues(horizontal = 10.dp, vertical = 2.dp)

private val MONTH_ABBREV = arrayOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")

// Apparent visual magnitude formulas from Mallama & Hilton (2018),
// Astronomy and Computing 25, 10–24 — the set adopted by the Astronomical
// Almanac starting in 2019 (IAU 2018). r = heliocentric distance (AU),
// delta = geocentric distance (AU), alphaDeg = phase angle (Sun–Planet–Earth),
// ringTiltBDeg = Saturn's ring tilt B (saturnicentric latitude of Earth).
// Secular brightening of the ice giants and the Uranus sub-Earth-latitude
// term (a few hundredths of a mag) are not included.
private fun apparentMagnitude(
    name: String, r: Double, delta: Double, alphaDeg: Double, ringTiltBDeg: Double = 0.0
): Double {
    val rDelta5log = 5.0 * log10(r * delta)
    val a = alphaDeg
    return when (name) {
        "Mercury" -> {
            // 6th-order polynomial valid for 2° < α < 170°.
            val phi = a * (6.3280e-2 + a * (-1.6336e-3 + a * (3.3644e-5 +
                a * (-3.4265e-7 + a * (1.6893e-9 - a * 3.0334e-12)))))
            -0.613 + rDelta5log + phi
        }
        "Venus" -> {
            // 4th-order, 0° ≤ α ≤ 163.7° (forward-scatter regime not reachable from Earth).
            val phi = a * (-1.044e-3 + a * (3.687e-4 + a * (-2.814e-6 + a * 8.938e-9)))
            -4.384 + rDelta5log + phi
        }
        "Mars" -> {
            // Earth-observable α ≤ ~47°.
            val phi = 0.02267 * a - 1.302e-4 * a * a
            -1.601 + rDelta5log + phi
        }
        "Jupiter" -> {
            // Earth-observable α ≤ 12°.
            val phi = -3.7e-4 * a + 6.16e-4 * a * a
            -9.395 + rDelta5log + phi
        }
        "Saturn" -> {
            // Globe + rings combined, α ≤ 6.5°, |B| ≤ 27°.
            val bRad = Math.toRadians(ringTiltBDeg)
            val sinAbsB = sin(abs(bRad))
            val sinB = sin(bRad)
            val phi = -1.825 * sinAbsB + 0.026 * abs(a) - 0.378 * sinB * exp(-2.25 * abs(a))
            -8.914 + rDelta5log + phi
        }
        "Uranus" -> {
            val phi = 6.587e-3 * a + 1.045e-4 * a * a
            -7.110 + rDelta5log + phi
        }
        "Neptune" -> {
            val phi = 7.944e-3 * a + 9.617e-5 * a * a
            -6.89 + rDelta5log + phi
        }
        else -> 0.0
    }
}

private data class PlanetSeries(
    val name: String,
    val symbol: String,
    val color: Color,
    val colorInt: Int,
    val samplesArcsec: FloatArray,
    val ringSamplesArcsec: FloatArray?,
)

private data class MonthTick(val dayOffset: Double, val month: Int, val year: Int)

@Composable
fun PlanetAngularSizeScreen(obs: ObserverState, onTimeDisplayChange: (Boolean) -> Unit) {
    // Shifted by the -1yr / +1yr buttons; 0 = window starts at today.
    var yearOffset by remember { mutableStateOf(0) }

    // Reference-pixel x of the tap/scrub line. Initialized to the chart's left edge so the
    // first render shows a line at today's date.
    var tappedRefX by remember { mutableStateOf<Float?>(CHART_LEFT_MARGIN) }

    val shiftedEpochSec = obs.now.epochSecond + yearOffset.toLong() * FORECAST_DAYS.toLong() * SECONDS_PER_DAY.toLong()
    val startJd = shiftedEpochSec.toDouble() / SECONDS_PER_DAY + UNIX_EPOCH_JD
    val dayKey = shiftedEpochSec / SECONDS_PER_DAY.toLong()

    val planets = remember { getOrreryPlanets().filter { it.name != "Earth" } }

    // Recomputed once per day — 7 planets × 366 samples per recomp would be wasteful per-minute.
    val series: List<PlanetSeries> = remember(dayKey) {
        planets.map { p ->
            val radiusKm = PLANET_RADIUS_KM[p.name] ?: 0.0
            val hasRings = p.name == "Saturn"
            val samples = FloatArray(SAMPLE_COUNT)
            val ringSamples = if (hasRings) FloatArray(SAMPLE_COUNT) else null
            for (i in 0 until SAMPLE_COUNT) {
                val jd = startJd + i * SAMPLE_STEP_DAYS
                val state = AstroEngine.getBodyState(p.name, jd)
                val distKm = state.distGeo * AU_KM
                samples[i] = (2.0 * radiusKm / distKm * ARCSEC_PER_RAD).toFloat()
                if (hasRings) {
                    ringSamples!![i] = (2.0 * SATURN_RING_OUTER_RADIUS_KM / distKm * ARCSEC_PER_RAD).toFloat()
                }
            }
            PlanetSeries(p.name, p.symbol, p.color, p.color.toArgb(), samples, ringSamples)
        }
    }

    val maxDiameters = remember(planets) { planets.map { MAX_DIAMETER_ARCSEC[it.name] ?: 0.0 } }
    // gapsArcsec[i] is the vertical gap above lane i; gapsArcsec[size] is the gap below the last lane.
    val gapsArcsec = remember(planets) {
        DoubleArray(planets.size + 1) { i ->
            if (i in 1 until planets.size &&
                planets[i - 1].name == "Uranus" && planets[i].name == "Neptune")
                URANUS_NEPTUNE_GAP_ARCSEC
            else
                MIN_GAP_ARCSEC
        }
    }
    val totalArcsecNeeded = remember(maxDiameters, gapsArcsec) {
        maxDiameters.sum() + gapsArcsec.sum()
    }
    val baselineArcsec = remember(maxDiameters, gapsArcsec) {
        DoubleArray(maxDiameters.size).apply {
            var cursor = gapsArcsec[0]
            for (i in maxDiameters.indices) {
                cursor += maxDiameters[i] / 2.0
                this[i] = cursor
                cursor += maxDiameters[i] / 2.0 + gapsArcsec[i + 1]
            }
        }
    }
    val tickLaneIdx = remember(maxDiameters) {
        maxDiameters.indices.maxByOrNull { maxDiameters[it] } ?: 0
    }

    val zone: ZoneId = if (obs.useStandardTime)
        ZoneOffset.ofTotalSeconds((obs.stdOffsetHours * 3600).toInt())
    else
        ZoneOffset.UTC

    val monthTicks: List<MonthTick> = remember(dayKey, zone) {
        val startInstant = Instant.ofEpochSecond(shiftedEpochSec)
        val endInstant = startInstant.plusSeconds(FORECAST_DAYS.toLong() * SECONDS_PER_DAY.toLong())
        val startLocal = ZonedDateTime.ofInstant(startInstant, zone)
        var cursor = startLocal.withDayOfMonth(1).withHour(0).withMinute(0).withSecond(0).withNano(0).plusMonths(1)
        val out = mutableListOf<MonthTick>()
        while (!cursor.toInstant().isAfter(endInstant)) {
            val tickEpochSec = cursor.toInstant().epochSecond
            val dayOffset = (tickEpochSec - shiftedEpochSec).toDouble() / SECONDS_PER_DAY
            out.add(MonthTick(dayOffset, cursor.monthValue, cursor.year))
            cursor = cursor.plusMonths(1)
        }
        out
    }
    // For section 0 (left of the first month tick) we need the month we started in.
    val startMonthOneBased = ZonedDateTime.ofInstant(Instant.ofEpochSecond(shiftedEpochSec), zone).monthValue

    val axisPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            strokeWidth = 1.5f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }
    val baselinePaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0x55, 0x55, 0x55)
            strokeWidth = 1f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }
    val labelPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            textSize = 22f
            typeface = Typeface.MONOSPACE
            isAntiAlias = true
            textAlign = Paint.Align.RIGHT
        }
    }
    val monthLetterPaint = remember {
        Paint().apply {
            color = android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
            textSize = 28f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val yearPaint = remember {
        Paint().apply {
            color = android.graphics.Color.WHITE
            textSize = 44f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val symbolPaint = remember {
        Paint().apply {
            textSize = 32f
            typeface = Typeface.DEFAULT_BOLD
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val lemonFillPaint = remember {
        Paint().apply {
            style = Paint.Style.FILL
            isAntiAlias = true
        }
    }
    val lemonPath = remember { Path() }
    val janTickPaint = remember {
        Paint().apply {
            color = android.graphics.Color.YELLOW
            strokeWidth = 4.5f
            style = Paint.Style.STROKE
            isAntiAlias = true
        }
    }
    val tapLinePaint = remember {
        Paint().apply {
            color = android.graphics.Color.WHITE
            strokeWidth = 5f
            style = Paint.Style.STROKE
            isAntiAlias = false
        }
    }
    val tapLabelPaint = remember {
        Paint().apply {
            color = android.graphics.Color.WHITE
            textSize = 44f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.LEFT
            isAntiAlias = true
        }
    }
    val tapDatePaint = remember {
        Paint().apply {
            color = android.graphics.Color.WHITE
            textSize = 28f
            typeface = Typeface.MONOSPACE
            textAlign = Paint.Align.CENTER
            isAntiAlias = true
        }
    }
    val tapDateFormatter = remember { DateTimeFormatter.ofPattern("d MMM yyyy") }

    Box(modifier = Modifier.fillMaxSize()) {
    Canvas(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .pointerInput(Unit) {
                val dScale = density / REFERENCE_DENSITY
                detectHorizontalDragGestures(
                    onDragStart = { offset -> tappedRefX = offset.x / dScale }
                ) { change, _ ->
                    tappedRefX = change.position.x / dScale
                }
            }
            .pointerInput(Unit) {
                // Convert raw device pixels to reference pixels (matches withDensityScaling).
                val dScale = density / REFERENCE_DENSITY
                detectTapGestures { offset ->
                    tappedRefX = offset.x / dScale
                }
            }
    ) {
        withDensityScaling { w, h ->

        val leftMargin = CHART_LEFT_MARGIN
        val rightMargin = 15f
        // Leaves room for the top row of buttons and the tap-line date label, which draws
        // ~30 rp above chartTop.
        val topMargin = 140f
        val bottomMargin = 125f

        val chartLeft = leftMargin
        val chartRight = w - rightMargin
        val chartTop = topMargin
        val chartBottom = h - bottomMargin
        val chartWidth = chartRight - chartLeft
        val chartHeight = chartBottom - chartTop

        val pxPerArcsec = chartHeight.toDouble() / totalArcsecNeeded

        fun dayToX(dayOffset: Double): Float =
            (chartLeft + (dayOffset / FORECAST_DAYS) * chartWidth).toFloat()
        fun laneCenterY(laneIdx: Int): Float = (chartTop + baselineArcsec[laneIdx] * pxPerArcsec).toFloat()

        drawIntoCanvas { nc ->
            val canvas = nc.nativeCanvas

            for ((i, s) in series.withIndex()) {
                val y = laneCenterY(i)
                canvas.drawLine(chartLeft, y, chartRight, y, baselinePaint)
                symbolPaint.color = s.colorInt
                canvas.drawText(s.symbol, leftMargin - 22f, y + 11f, symbolPaint)
            }

            // Ticks anchored to the largest lane so the full ±halfMax range fits within its band.
            val tickLaneSpanArcsec = maxDiameters[tickLaneIdx]
            val tickLaneY = laneCenterY(tickLaneIdx)
            val halfMax = tickLaneSpanArcsec / 2.0
            val tickStep = when {
                tickLaneSpanArcsec >= 80.0 -> 20.0
                tickLaneSpanArcsec >= 30.0 -> 10.0
                tickLaneSpanArcsec >= 12.0 -> 5.0
                else -> 2.0
            }
            var tickArcsec = -floor(halfMax / tickStep) * tickStep
            while (tickArcsec <= halfMax) {
                val y = tickLaneY + (tickArcsec * pxPerArcsec).toFloat()
                canvas.drawLine(leftMargin - 6f, y, leftMargin, y, axisPaint)
                // Skip the 0″ label — it sits at the tick-anchor lane's baseline and would
                // overlap that planet's symbol drawn at the same y.
                if (abs(tickArcsec) >= 0.001) {
                    val label = "%.0f\u2033".format(abs(tickArcsec))
                    canvas.drawText(label, leftMargin - 8f, y + 7f, labelPaint)
                }
                tickArcsec += tickStep
            }

            fun buildLemon(baselineY: Float, samples: FloatArray) {
                lemonPath.reset()
                for (k in 0 until SAMPLE_COUNT) {
                    val x = dayToX(k * SAMPLE_STEP_DAYS)
                    val y = baselineY - (samples[k] / 2.0 * pxPerArcsec).toFloat()
                    if (k == 0) lemonPath.moveTo(x, y) else lemonPath.lineTo(x, y)
                }
                for (k in SAMPLE_COUNT - 1 downTo 0) {
                    val x = dayToX(k * SAMPLE_STEP_DAYS)
                    val y = baselineY + (samples[k] / 2.0 * pxPerArcsec).toFloat()
                    lemonPath.lineTo(x, y)
                }
                lemonPath.close()
            }
            for ((i, s) in series.withIndex()) {
                val baselineY = laneCenterY(i)
                // Rings drawn first (wider, white) so the disk lemon overlays them.
                if (s.ringSamplesArcsec != null) {
                    buildLemon(baselineY, s.ringSamplesArcsec)
                    lemonFillPaint.color = android.graphics.Color.WHITE
                    canvas.drawPath(lemonPath, lemonFillPaint)
                }
                buildLemon(baselineY, s.samplesArcsec)
                lemonFillPaint.color = s.colorInt
                canvas.drawPath(lemonPath, lemonFillPaint)
            }

            val tickY = chartBottom
            val tickLen = 6f
            val janTickLen = tickLen * 10f
            for (t in monthTicks) {
                val x = dayToX(t.dayOffset)
                if (t.month == 1) {
                    canvas.drawLine(x, tickY, x, tickY + janTickLen, janTickPaint)
                } else {
                    canvas.drawLine(x, tickY, x, tickY + tickLen, axisPaint)
                }
            }

            // Section i (0-based) covers the month starting at tick i-1, or for i=0 the month
            // in which the forecast starts.
            val letterY = chartBottom + 35f
            val boundaries = mutableListOf<Float>()
            boundaries.add(chartLeft)
            for (t in monthTicks) boundaries.add(dayToX(t.dayOffset))
            boundaries.add(chartRight)
            for (i in 0 until boundaries.size - 1) {
                val leftX = boundaries[i]
                val rightX = boundaries[i + 1]
                if (rightX - leftX < 14f) continue
                val monthOneBased = if (i == 0) startMonthOneBased else monthTicks[i - 1].month
                val label = MONTH_ABBREV[monthOneBased - 1]
                val cx = (leftX + rightX) / 2f
                monthLetterPaint.color = if (monthOneBased == 1)
                    android.graphics.Color.YELLOW
                else
                    android.graphics.Color.rgb(0xAD, 0xD8, 0xE6)
                canvas.save()
                canvas.rotate(90f, cx, letterY)
                canvas.drawText(label, cx, letterY, monthLetterPaint)
                canvas.restore()
            }

            val yearY = chartBottom + 105f
            for (t in monthTicks) {
                if (t.month != 7) continue
                val label = t.year.toString()
                val halfWidth = yearPaint.measureText(label) / 2f
                // If the July-1 tick sits too close to an edge, shift the label toward
                // the center just enough to keep it fully on-screen.
                val x = dayToX(t.dayOffset).coerceIn(chartLeft + halfWidth, chartRight - halfWidth)
                canvas.drawText(label, x, yearY, yearPaint)
            }

            // Tap inspection: a vertical line at the tap x, per-planet labels to one side,
            // and the tapped date above the chart. Line color is planet-specific (see
            // bandLineColor) so it stays visible against each lemon's fill.
            tappedRefX?.let { rawX ->
                val tapX = rawX.coerceIn(chartLeft, chartRight)

                val dayOffset = ((tapX - chartLeft) / chartWidth) * FORECAST_DAYS
                val tappedEpochSec = shiftedEpochSec + (dayOffset * SECONDS_PER_DAY).toLong()
                val tappedLocalDate = Instant.ofEpochSecond(tappedEpochSec).atZone(zone).toLocalDate()
                val noonInstant = tappedLocalDate.atTime(12, 0).atZone(zone).toInstant()
                val jdAtNoon = noonInstant.epochSecond.toDouble() / SECONDS_PER_DAY + UNIX_EPOCH_JD

                val earthSunDist = AstroEngine.getBodyState("Sun", jdAtNoon).distGeo
                val diskArcsecAt = DoubleArray(planets.size)
                val ringArcsecAt = DoubleArray(planets.size)
                val magnitudes = DoubleArray(planets.size)
                val phaseAnglesDeg = DoubleArray(planets.size)
                val ringTiltBDegAt = DoubleArray(planets.size)
                for ((idx, p) in planets.withIndex()) {
                    val radiusKm = PLANET_RADIUS_KM[p.name] ?: continue
                    val state = AstroEngine.getBodyState(p.name, jdAtNoon)
                    val distKm = state.distGeo * AU_KM
                    diskArcsecAt[idx] = 2.0 * radiusKm / distKm * ARCSEC_PER_RAD
                    val r = state.distSun
                    val delta = state.distGeo
                    phaseAnglesDeg[idx] = Math.toDegrees(phaseAngleRad(r, delta, earthSunDist))
                    if (p.name == "Saturn") {
                        ringTiltBDegAt[idx] = SaturnMoonEngine.calculateRingTiltB(
                            state.eclipticLon, state.eclipticLat, jdAtNoon)
                        ringArcsecAt[idx] = 2.0 * SATURN_RING_OUTER_RADIUS_KM / distKm * ARCSEC_PER_RAD
                    }
                    magnitudes[idx] = apparentMagnitude(p.name, r, delta, phaseAnglesDeg[idx], ringTiltBDegAt[idx])
                }

                fun drawSeg(y1: Float, y2: Float, lineColor: Int) {
                    if (y2 > y1) {
                        tapLinePaint.color = lineColor
                        canvas.drawLine(tapX, y1, tapX, y2, tapLinePaint)
                    }
                }
                // Line color by planet: gaps are white, Venus is black (so the line is
                // visible on Venus's white fill), Saturn is red across its whole ring extent
                // (ring halo + disk), Uranus is magenta to stand out against the green disk,
                // everything else white.
                fun bandLineColor(s: PlanetSeries): Int = when (s.name) {
                    "Venus" -> android.graphics.Color.BLACK
                    "Saturn" -> android.graphics.Color.RED
                    "Uranus" -> android.graphics.Color.MAGENTA
                    else -> android.graphics.Color.WHITE
                }
                val white = android.graphics.Color.WHITE
                var prevY = chartTop
                for ((idx, s) in series.withIndex()) {
                    val baselineY = laneCenterY(idx)
                    val diskHalfPx = (diskArcsecAt[idx] / 2.0 * pxPerArcsec).toFloat()
                    val diskTop = baselineY - diskHalfPx
                    val diskBottom = baselineY + diskHalfPx
                    val bandColor = bandLineColor(s)
                    if (s.ringSamplesArcsec != null) {
                        val ringHalfPx = (ringArcsecAt[idx] / 2.0 * pxPerArcsec).toFloat()
                        val ringTop = baselineY - ringHalfPx
                        val ringBottom = baselineY + ringHalfPx
                        drawSeg(prevY, ringTop, white)
                        drawSeg(ringTop, diskTop, bandColor)
                        drawSeg(diskTop, diskBottom, bandColor)
                        drawSeg(diskBottom, ringBottom, bandColor)
                        prevY = ringBottom
                    } else {
                        drawSeg(prevY, diskTop, white)
                        drawSeg(diskTop, diskBottom, bandColor)
                        prevY = diskBottom
                    }
                }
                drawSeg(prevY, chartBottom, white)

                // Put labels on the side that has more room: right of the line when the line
                // is in the left half of the plot, left of the line when it's in the right half.
                val labelOnLeft = tapX > (chartLeft + chartRight) / 2f
                tapLabelPaint.textAlign = if (labelOnLeft) Paint.Align.RIGHT else Paint.Align.LEFT
                val labelX = if (labelOnLeft) tapX - 8f else tapX + 8f
                for ((idx, s) in series.withIndex()) {
                    val y = laneCenterY(idx)
                    tapLabelPaint.color = bandLineColor(s)
                    when (s.name) {
                        "Saturn" -> {
                            canvas.drawText(
                                "%.1f\u2033/%.1f\u2033  %+.1fm".format(
                                    diskArcsecAt[idx], ringArcsecAt[idx], magnitudes[idx]),
                                labelX, y + 14f, tapLabelPaint)
                            canvas.drawText(
                                "Ring Tilt %+.1f\u00B0".format(ringTiltBDegAt[idx]),
                                labelX, y + 14f + 52f, tapLabelPaint)
                        }
                        // Illumination for Uranus/Neptune is essentially always 100%, so omit.
                        "Uranus", "Neptune" -> {
                            canvas.drawText(
                                "%.1f\u2033  %+.1fm".format(diskArcsecAt[idx], magnitudes[idx]),
                                labelX, y + 14f, tapLabelPaint)
                        }
                        else -> {
                            // Illuminated fraction from phase angle: k = (1 + cos α) / 2.
                            val illumPct = (1.0 + cos(Math.toRadians(phaseAnglesDeg[idx]))) / 2.0 * 100.0
                            canvas.drawText(
                                "%.1f\u2033  %+.1fm  %.0f%%".format(
                                    diskArcsecAt[idx], magnitudes[idx], illumPct),
                                labelX, y + 14f, tapLabelPaint)
                        }
                    }
                }

                // Date above the top of the line. Clamped to the canvas so it doesn't clip
                // when the tap is near an edge.
                val dateStr = tappedLocalDate.format(tapDateFormatter)
                val dateHalfWidth = tapDatePaint.measureText(dateStr) / 2f
                val dateBaseline = chartTop - tapDatePaint.descent() - 2f
                val dateX = tapX.coerceIn(dateHalfWidth, w - dateHalfWidth)
                canvas.drawText(dateStr, dateX, dateBaseline, tapDatePaint)
            }
        }

        }
    }

    val shiftYear: (Int) -> Unit = { delta ->
        yearOffset += delta
        tappedRefX = CHART_LEFT_MARGIN
    }
    YearShiftButton("-1yr", Alignment.TopStart) { shiftYear(-1) }
    YearShiftButton("+1yr", Alignment.TopEnd) { shiftYear(+1) }
    if (yearOffset != 0) {
        TextButton(
            onClick = { yearOffset = 0 },
            colors = ButtonDefaults.textButtonColors(contentColor = Color(0xFF00FF00)),
            modifier = Modifier
                .align(Alignment.TopCenter)
                .padding(8.dp)
        ) {
            Text("Reset Time", fontWeight = FontWeight.Bold)
        }
    }
    }
}

@Composable
private fun BoxScope.YearShiftButton(label: String, alignment: Alignment, onClick: () -> Unit) {
    Button(
        onClick = onClick,
        colors = ButtonDefaults.buttonColors(
            containerColor = Color.DarkGray,
            contentColor = Color.White,
        ),
        contentPadding = YEAR_BUTTON_PADDING,
        modifier = Modifier
            .align(alignment)
            .padding(4.dp)
            .height(28.dp)
    ) {
        Text(label, fontWeight = FontWeight.Bold, fontSize = 11.sp)
    }
}
