#!/usr/bin/env python3
"""
Generate zodiac_map_data.bin — precomputed zodiac constellation boundary segments
and label positions for the Android Orrery sky map.

Reads constellation_boundaries.bin (generated by generateConstellationBoundaries.py),
rasterizes zodiac boundaries on a fine grid, merges collinear segments, computes
label positions, and writes the result to the assets directory.

Binary output format (little-endian):
    uint16  segmentCount
    uint16  labelCount
    Repeated segmentCount times (16 bytes each):
        float32  ra1   (hours, B1875.0)
        float32  dec1  (degrees)
        float32  ra2   (hours, B1875.0)
        float32  dec2  (degrees)
    Repeated labelCount times (9 bytes each):
        float32  ra    (hours, B1875.0)
        float32  dec   (degrees)
        uint8    constellationIndex
"""

import struct
import os
from collections import defaultdict

ASSETS_DIR = '../app/src/main/assets'

# Map boundaries: Dec -50° to +50°
DEC_MIN = -50.0
DEC_MAX = 50.0
DEC_RANGE = DEC_MAX - DEC_MIN

# Fine grid resolution (10x the app's in-app grid)
RA_STEPS = 3600
DEC_STEPS = 1000
RA_STEP = 24.0 / RA_STEPS
DEC_STEP = DEC_RANGE / DEC_STEPS

# Zodiac constellation indices (matching ConstellationBoundary.kt constellationNames)
ZODIAC_INDICES = {4, 6, 11, 21, 37, 45, 47, 66, 71, 76, 77, 85}

# For diagnostic output
CONSTELLATION_NAMES = [
    "Andromeda", "Antlia", "Apus", "Aquila", "Aquarius", "Ara", "Aries",
    "Auriga", "Boötes", "Caelum", "Camelopardalis", "Capricornus", "Carina",
    "Cassiopeia", "Centaurus", "Cepheus", "Cetus", "Chamaeleon", "Circinus",
    "Canis Major", "Canis Minor", "Cancer", "Columba", "Coma Berenices",
    "Corona Australis", "Corona Borealis", "Crater", "Crux", "Corvus",
    "Canes Venatici", "Cygnus", "Delphinus", "Dorado", "Draco", "Equuleus",
    "Eridanus", "Fornax", "Gemini", "Grus", "Hercules", "Horologium",
    "Hydra", "Hydrus", "Indus", "Lacerta", "Leo", "Lepus", "Libra",
    "Leo Minor", "Lupus", "Lynx", "Lyra", "Mensa", "Microscopium",
    "Monoceros", "Musca", "Norma", "Octans", "Ophiuchus", "Orion", "Pavo",
    "Pegasus", "Perseus", "Phoenix", "Pictor", "Piscis Austrinus", "Pisces",
    "Puppis", "Pyxis", "Reticulum", "Sculptor", "Scorpius", "Scutum",
    "Serpens", "Sextans", "Sagitta", "Sagittarius", "Taurus", "Telescopium",
    "Triangulum Australe", "Triangulum", "Tucana", "Ursa Major", "Ursa Minor",
    "Vela", "Virgo", "Volans", "Vulpecula",
]


def load_boundaries(path):
    """Load constellation boundary records from binary file."""
    records = []
    with open(path, 'rb') as f:
        while True:
            data = f.read(13)
            if len(data) < 13:
                break
            ra_low, ra_high, dec_low = struct.unpack('<fff', data[:12])
            idx = data[12]
            records.append((ra_low, ra_high, dec_low, idx))
    return records


def build_bands(records):
    """
    Group records into declination bands, sorted by decreasing decLow.
    Each band contains all records at the same decLow value; their RA ranges
    partition 0–24h completely.
    """
    bands = []
    current_dec = None
    current_recs = []
    for rec in records:
        dec_low = rec[2]
        if dec_low != current_dec:
            if current_recs:
                bands.append((current_dec, current_recs))
            current_dec = dec_low
            current_recs = [rec]
        else:
            current_recs.append(rec)
    if current_recs:
        bands.append((current_dec, current_recs))
    return bands


def find_band_index(bands, dec):
    """Binary search for the first band with decLow <= dec."""
    lo, hi = 0, len(bands)
    while lo < hi:
        mid = (lo + hi) // 2
        if bands[mid][0] > dec:
            lo = mid + 1
        else:
            hi = mid
    return lo


def find_in_band(band_recs, ra):
    """Find constellation index within a declination band for given RA."""
    for ra_low, ra_high, _, idx in band_recs:
        if ra >= ra_low and ra < ra_high:
            return idx
    return -1


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    boundary_path = os.path.join(script_dir, ASSETS_DIR, 'constellation_boundaries.bin')
    output_path = os.path.join(script_dir, ASSETS_DIR, 'zodiac_map_data.bin')

    print(f"Loading boundaries from {boundary_path}")
    records = load_boundaries(boundary_path)
    print(f"Loaded {len(records)} boundary records")

    bands = build_bands(records)
    print(f"Organized into {len(bands)} declination bands")

    # Build fine grid — each cell stores constellation index at its center
    print(f"Building {RA_STEPS} x {DEC_STEPS} grid...")
    grid = [[0] * DEC_STEPS for _ in range(RA_STEPS)]
    for di in range(DEC_STEPS):
        if di % 100 == 0:
            print(f"  Dec row {di}/{DEC_STEPS}...")
        dec = DEC_MIN + (di + 0.5) * DEC_STEP
        bi_start = find_band_index(bands, dec)
        for ri in range(RA_STEPS):
            ra = (ri + 0.5) * RA_STEP
            found = -1
            for bi in range(bi_start, len(bands)):
                found = find_in_band(bands[bi][1], ra)
                if found != -1:
                    break
            grid[ri][di] = found
    print("Grid complete")

    # --- Extract raw boundary segments ---
    print("Extracting boundary segments...")
    raw_h = []  # (ra1, ra2, dec) — horizontal
    raw_v = []  # (ra, dec1, dec2) — vertical

    # Horizontal edges: between vertically adjacent cells
    for ri in range(RA_STEPS):
        ra1 = ri * RA_STEP
        ra2 = (ri + 1) * RA_STEP
        for di in range(DEC_STEPS - 1):
            below = grid[ri][di]
            above = grid[ri][di + 1]
            if below != above and (below in ZODIAC_INDICES or above in ZODIAC_INDICES):
                dec = DEC_MIN + (di + 1) * DEC_STEP
                raw_h.append((ra1, ra2, dec))
        # Bottom map edge
        if grid[ri][0] in ZODIAC_INDICES:
            raw_h.append((ra1, ra2, DEC_MIN))
        # Top map edge
        if grid[ri][DEC_STEPS - 1] in ZODIAC_INDICES:
            raw_h.append((ra1, ra2, DEC_MAX))

    # Vertical edges: between horizontally adjacent cells
    for di in range(DEC_STEPS):
        dec1 = DEC_MIN + di * DEC_STEP
        dec2 = DEC_MIN + (di + 1) * DEC_STEP
        for ri in range(RA_STEPS - 1):
            left = grid[ri][di]
            right = grid[ri + 1][di]
            if left != right and (left in ZODIAC_INDICES or right in ZODIAC_INDICES):
                ra = (ri + 1) * RA_STEP
                raw_v.append((ra, dec1, dec2))
        # Wrap at RA=0/24h
        first = grid[0][di]
        last = grid[RA_STEPS - 1][di]
        if first != last and (first in ZODIAC_INDICES or last in ZODIAC_INDICES):
            raw_v.append((0.0, dec1, dec2))

    print(f"Raw segments: {len(raw_h)} horizontal, {len(raw_v)} vertical")

    # --- Merge collinear horizontal segments (same dec, adjacent in RA) ---
    h_by_dec = defaultdict(list)
    for ra1, ra2, dec in raw_h:
        h_by_dec[dec].append((ra1, ra2))

    merged_segments = []
    for dec in sorted(h_by_dec.keys()):
        segs = sorted(h_by_dec[dec])
        cur_ra1, cur_ra2 = segs[0]
        for ra1, ra2 in segs[1:]:
            if abs(ra1 - cur_ra2) < RA_STEP * 0.5:
                cur_ra2 = ra2
            else:
                merged_segments.append((cur_ra1, dec, cur_ra2, dec))
                cur_ra1, cur_ra2 = ra1, ra2
        merged_segments.append((cur_ra1, dec, cur_ra2, dec))

    h_count = len(merged_segments)

    # --- Merge collinear vertical segments (same ra, adjacent in dec) ---
    v_by_ra = defaultdict(list)
    for ra, dec1, dec2 in raw_v:
        v_by_ra[ra].append((dec1, dec2))

    for ra in sorted(v_by_ra.keys()):
        segs = sorted(v_by_ra[ra])
        cur_dec1, cur_dec2 = segs[0]
        for dec1, dec2 in segs[1:]:
            if abs(dec1 - cur_dec2) < DEC_STEP * 0.5:
                cur_dec2 = dec2
            else:
                merged_segments.append((ra, cur_dec1, ra, cur_dec2))
                cur_dec1, cur_dec2 = dec1, dec2
        merged_segments.append((ra, cur_dec1, ra, cur_dec2))

    v_count = len(merged_segments) - h_count
    print(f"Merged segments: {h_count} horizontal + {v_count} vertical = {len(merged_segments)} total")

    # --- Compute label positions ---
    # Single pass over grid to collect per-constellation stats
    zodiac_cols = defaultdict(set)
    zodiac_min_dec = {}
    for ri in range(RA_STEPS):
        for di in range(DEC_STEPS):
            idx = grid[ri][di]
            if idx in ZODIAC_INDICES:
                zodiac_cols[idx].add(ri)
                dec = DEC_MIN + (di + 0.5) * DEC_STEP
                if idx not in zodiac_min_dec or dec < zodiac_min_dec[idx]:
                    zodiac_min_dec[idx] = dec

    labels = []
    print("Label positions:")
    for zodiac_idx in sorted(ZODIAC_INDICES):
        col_set = zodiac_cols.get(zodiac_idx)
        if not col_set:
            continue

        sorted_cols = sorted(col_set)

        # Find largest gap in RA columns to determine east/west extent
        max_gap = 0
        gap_after_idx = 0
        for i in range(len(sorted_cols) - 1):
            gap = sorted_cols[i + 1] - sorted_cols[i]
            if gap > max_gap:
                max_gap = gap
                gap_after_idx = i
        wrap_gap = (sorted_cols[0] + RA_STEPS) - sorted_cols[-1]
        if wrap_gap > max_gap:
            gap_after_idx = len(sorted_cols) - 1

        western_col = sorted_cols[(gap_after_idx + 1) % len(sorted_cols)]
        eastern_col = sorted_cols[gap_after_idx]
        western_ra = (western_col + 0.5) * RA_STEP
        eastern_ra = (eastern_col + 0.5) * RA_STEP

        if eastern_ra >= western_ra:
            mid_ra = (western_ra + eastern_ra) / 2.0
        else:
            mid_ra = (western_ra + eastern_ra + 24.0) / 2.0
            if mid_ra >= 24.0:
                mid_ra -= 24.0

        label_dec = zodiac_min_dec[zodiac_idx] - 8.0
        labels.append((mid_ra, label_dec, zodiac_idx))

        name = CONSTELLATION_NAMES[zodiac_idx]
        print(f"  {name:15s} (idx={zodiac_idx:2d}): RA={mid_ra:6.3f}h  Dec={label_dec:+7.1f} deg")

    # --- Write binary output ---
    seg_count = len(merged_segments)
    label_count = len(labels)

    with open(output_path, 'wb') as f:
        f.write(struct.pack('<HH', seg_count, label_count))
        for ra1, dec1, ra2, dec2 in merged_segments:
            f.write(struct.pack('<ffff', ra1, dec1, ra2, dec2))
        for ra, dec, idx in labels:
            f.write(struct.pack('<ffB', ra, dec, idx))

    file_size = os.path.getsize(output_path)
    print(f"\nWrote {output_path}")
    print(f"  Header:   4 bytes")
    print(f"  Segments: {seg_count} x 16 = {seg_count * 16} bytes")
    print(f"  Labels:   {label_count} x 9 = {label_count * 9} bytes")
    print(f"  Total:    {file_size} bytes")


if __name__ == '__main__':
    main()
